language: python
dist: xenial
python:
  - "3.7"

cache:
  - pip

install:
  - pip install -U pip pipenv
  - pipenv install -v -d --skip-lock
  - pipenv install -v six==1.12 --skip-lock

script:
  - make test
